### ISSUE TITLE
npm install error 

### ISSUE THREAD

**Issue by lazywhite** [AngularShowcase/ng2-bootstrap-sbadmin#17]
```

[02:49:42] Finished 'check.versions' after 17 ms
npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/white/.nvm/versions/node/v4.4.4/bin/node" "/Users/white/.nvm/versions/node/v4.4.4/bin/npm" "install"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package rxjs@5.0.0-beta.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angular2@2.0.0-beta.15 wants rxjs@5.0.0-beta.2
npm ERR! peerinvalid Peer @angular/core@2.0.0-rc.1 wants rxjs@5.0.0-beta.6

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/white/ng2-bootstrap-sbadmin/npm-debug.log


```

I already lost my faith about Nodejs and Angular2

**Comment by ludohenin** [comment]
Keep faith @lazywhite :)
I just did a fresh install this morning, it worked like a charm.
May try `npm cache clean` prior `npm install` (I actually always do it now)

**Comment by ludohenin** [comment]
oops the install I did was on the upstream seed, not this repo.

**Comment by icarys29** [comment]
Hello,

I tried to install it but I have this error (nodejs: v6.1.0, npm: 3.8.6) :

# 

[23:56:56] Finished 'check.versions' after 17 ms
ngular2-seed@0.0.0 /Desktop/Dev/ng2-bootstrap-sbadmin
├── UNMET PEER DEPENDENCY @angular/common@^2.0.0-rc.1
├── UNMET PEER DEPENDENCY @angular/compiler@^2.0.0-rc.1
├── UNMET PEER DEPENDENCY @angular/core@^2.0.0-rc.1
├── UNMET PEER DEPENDENCY @angular/platform-browser@^2.0.0-rc.1

# ├── UNMET PEER DEPENDENCY @angular/platform-browser-dynamic@^2.0.0-rc.1

I tried to clean the cache (npm cache clean) and also tried to change the version of nodejs (v5.10.1) but without success. Them I tried to install it on cloud9 to see if it was an environment issue but I got the same error.

Am I missing something ?
Thank you in advance for your help.

**Comment by ludohenin** [comment]
> Am I missing something ?

Looks like the peer dependencies aren't installed.

**Comment by icarys29** [comment]
I Agree but I tried to do "npm install @angular/..." but it did not work. And unless I am mistaken, the peer dependencies should be also installed by npm, no ?

**Comment by ludohenin** [comment]
yes. `npm install @angular/core@2.0.0-rc.1 --save`

**Comment by lazywhite** [comment]
whats the difference between @angular/<> and angular2/<>

**Comment by ludohenin** [comment]
initially, angular was published to npm as one package `angular2` but now it is under a organization scope `@angular` and split into multiple package (to be installed independently) `core`, `router` ...
they are imported (required) following the directory structure `@angular/core` ...

**Comment by icarys29** [comment]
Hello again.

I am still struggling with the installation.
I tried on Windows, Linux, Mac but without success.
I have just one question:
Did you succeed to install this demo from scratch just following the procedure :

```
git clone https://github.com/AngularShowcase/ng2-bootstrap-sbadmin.git
cd ng2-bootstrap-sbadmin
npm install   # clean npm cache & delete node_modules folder if you get an error
npm start     # start with --env dev
```

A feedback would be really appreciated.
Regards

**Comment by unnijeevan** [comment]
From the package.Json it seems the peer dependencies will be an issue . The dependency for ng2-bootstrap is caret (^) which will fetch 1.0.16 version instead of 1.0.13 .The 1.0.16 has a dependency on  angular rc1 while for this project the angular version is beta. I think you need to update the package.json with rc1 angular dependency or force other package dependencies by getting rid of caret(^) before you run the install.

**Comment by ScriptProdigy** [comment]
Replicated issue from the OP. Any solutions yet?

**Comment by bernardocaldas** [comment]
Same here...

**Comment by bestori** [comment]
+1

**Comment by hillriegel** [comment]
me too

**Comment by n0daft** [comment]
I have the same problem.
@unnijeevan if you delete the caret in front of "ng2-bootstrap": "1.0.13", the UNMET PEER DEPENDENCY disappears. There are actually no errors while install. However, during start the following errors appear:

`[11:55:20] Starting 'build.js.dev'...
src/client/app/components/header/header.ts(4,9): error TS2305: Module '"/Users/n0daft/Documents/Entwicklung/Test/ng2-bootstrap-sbadmin-master/node_modules/ng2-bootstrap/components/dropdown"' has no exported member 'DropdownDirective'.
src/client/app/components/header/header.ts(4,28): error TS2305: Module '"/Users/n0daft/Documents/Entwicklung/Test/ng2-bootstrap-sbadmin-master/node_modules/ng2-bootstrap/components/dropdown"' has no exported member 'DropdownMenuDirective'.
src/client/app/components/header/header.ts(4,51): error TS2305: Module '"/Users/n0daft/Documents/Entwicklung/Test/ng2-bootstrap-sbadmin-master/node_modules/ng2-bootstrap/components/dropdown"' has no exported member 'DropdownToggleDirective'.
`

If you however use Angular version "2.0.0-rc.1" it will not install since the version is not found: 
`No compatible version found: angular2@2.0.0-rc.1`

**Comment by jcoryatjr** [comment]
I'm having the same problem lazywhite is having.  Was there ever a fix identified?

**Comment by BrunoFenzl** [comment]
had the same here, had to change dependencies by hand but I#m stuck on the 'Loading…' index page
